# Generated by Django 5.2.5 on 2025-08-31 12:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import manga.models.base
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_type', models.CharField(choices=[('user_register', 'User Registration'), ('user_login', 'User Login'), ('manga_create', 'Manga Created'), ('manga_update', 'Manga Updated'), ('manga_delete', 'Manga Deleted'), ('chapter_publish', 'Chapter Published'), ('comment_create', 'Comment Created'), ('rating_create', 'Rating Created'), ('admin_action', 'Admin Action'), ('system_error', 'System Error')], max_length=50)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, max_length=500)),
                ('metadata', models.JSONField(default=dict, help_text='Additional structured data')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=20)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookmarkPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_number', models.PositiveIntegerField()),
                ('note', models.TextField(blank=True, max_length=200)),
                ('is_private', models.BooleanField(default=False)),
                ('bookmark_type', models.CharField(choices=[('favorite_scene', 'Favorite Scene'), ('important_plot', 'Important Plot Point'), ('funny_moment', 'Funny Moment'), ('character_development', 'Character Development'), ('other', 'Other')], default='other', max_length=254)),
            ],
            options={
                'verbose_name': 'Bookmarked Page',
                'verbose_name_plural': 'Bookmarked Pages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChapterView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, max_length=500)),
                ('referrer', models.URLField(blank=True)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('pages_viewed', models.PositiveIntegerField(default=0)),
                ('reading_time', models.PositiveIntegerField(default=0, help_text='Reading time in seconds')),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet')], default='desktop', max_length=20)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Chapter View',
                'verbose_name_plural': 'Chapter Views',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(max_length=1000)),
                ('is_spoiler', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('is_pinned', models.BooleanField(default=False, help_text='Pinned by moderator')),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('dislikes_count', models.PositiveIntegerField(default=0)),
                ('reply_count', models.PositiveIntegerField(default=0)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vote_type', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10)),
            ],
            options={
                'verbose_name': 'Comment Like',
                'verbose_name_plural': 'Comment Likes',
            },
        ),
        migrations.CreateModel(
            name='MangaGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Main genre for this manga')),
            ],
            options={
                'verbose_name': 'Manga Genre',
                'verbose_name_plural': 'Manga Genres',
            },
        ),
        migrations.CreateModel(
            name='MangaRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveIntegerField(help_text='Rating from 1 to 10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('review_title', models.CharField(blank=True, max_length=200)),
                ('review_text', models.TextField(blank=True, max_length=2000)),
                ('is_spoiler', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=True)),
                ('helpful_votes', models.PositiveIntegerField(default=0)),
                ('total_votes', models.PositiveIntegerField(default=0)),
                ('would_recommend', models.BooleanField(default=True)),
                ('favorite_aspect', models.CharField(blank=True, help_text='What user liked most', max_length=100)),
            ],
            options={
                'verbose_name': 'Manga Rating',
                'verbose_name_plural': 'Manga Ratings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MangaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Manga Tag',
                'verbose_name_plural': 'Manga Tags',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('new_chapter', 'New Chapter'), ('manga_update', 'Manga Update'), ('comment_reply', 'Comment Reply'), ('favorite_update', 'Favorite Update'), ('system_message', 'System Message'), ('rating_like', 'Rating Liked'), ('comment_like', 'Comment Liked')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(max_length=500)),
                ('action_url', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('is_email_sent', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RatingHelpful',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vote_type', models.CharField(choices=[('helpful', 'Helpful'), ('not_helpful', 'Not Helpful')], max_length=15)),
            ],
            options={
                'verbose_name': 'Rating Helpfulness Vote',
                'verbose_name_plural': 'Rating Helpfulness Votes',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('data_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('json', 'JSON')], default='string', max_length=20)),
                ('is_public', models.BooleanField(default=False, help_text='Can be accessed by non-admin users')),
                ('category', models.CharField(default='general', help_text='Setting category for organization', max_length=50)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
                'ordering': ['category', 'key'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('theme', 'Theme'), ('demographic', 'Demographic'), ('format', 'Format'), ('status', 'Status'), ('content', 'Content Warning')], default='theme', max_length=20)),
                ('color_code', models.CharField(default='#6c757d', max_length=7)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('is_system', models.BooleanField(default=False, help_text='System-generated tag')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['manga', 'chapter_number'], 'verbose_name': 'Chapter', 'verbose_name_plural': 'Chapters'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'Genre', 'verbose_name_plural': 'Genres'},
        ),
        migrations.AlterModelOptions(
            name='manga',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Manga', 'verbose_name_plural': 'Manga'},
        ),
        migrations.AlterModelOptions(
            name='readinghistory',
            options={'ordering': ['-last_read_at'], 'verbose_name': 'Reading History', 'verbose_name_plural': 'Reading Histories'},
        ),
        migrations.AlterModelOptions(
            name='userfavorite',
            options={'ordering': ['-added_at'], 'verbose_name': 'User Favorite', 'verbose_name_plural': 'User Favorites'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.RemoveIndex(
            model_name='chapter',
            name='manga_chapt_manga_i_d04498_idx',
        ),
        migrations.RemoveIndex(
            model_name='chapter',
            name='manga_chapt_release_2f7a34_idx',
        ),
        migrations.RemoveIndex(
            model_name='manga',
            name='manga_manga_status_1bbfac_idx',
        ),
        migrations.RemoveIndex(
            model_name='manga',
            name='manga_manga_rating_8efccc_idx',
        ),
        migrations.RemoveIndex(
            model_name='manga',
            name='manga_manga_view_co_e17a85_idx',
        ),
        migrations.RenameField(
            model_name='manga',
            old_name='rating',
            new_name='average_rating',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='images',
        ),
        migrations.AddField(
            model_name='chapter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapter',
            name='external_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='chapter',
            name='external_source',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='chapter',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chapter',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chapter',
            name='meta_description',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='chapter',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='chapter',
            name='original_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='pages',
            field=models.JSONField(default=list, help_text='Array of image URLs or file paths'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='reading_time_avg',
            field=models.PositiveIntegerField(default=0, help_text='Average reading time in seconds'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='scheduled_release',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='size_mb',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='chapter',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='unique_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chapter',
            name='unlock_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='volume_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='genre',
            name='icon',
            field=models.CharField(blank=True, help_text='FontAwesome icon class', max_length=50),
        ),
        migrations.AddField(
            model_name='genre',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='genre',
            name='manga_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='genre',
            name='parent_genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manga.genre'),
        ),
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='manga',
            name='alternative_titles',
            field=models.JSONField(default=dict, help_text='Alternative titles in different languages'),
        ),
        migrations.AddField(
            model_name='manga',
            name='banner_image',
            field=models.ImageField(blank=True, upload_to='manga/banners/'),
        ),
        migrations.AddField(
            model_name='manga',
            name='bookmark_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='manga',
            name='comment_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='manga',
            name='content_rating',
            field=models.CharField(choices=[('safe', 'Safe'), ('suggestive', 'Suggestive'), ('erotica', 'Erotica'), ('pornographic', 'Pornographic')], default='safe', max_length=20),
        ),
        migrations.AddField(
            model_name='manga',
            name='external_id',
            field=models.CharField(blank=True, help_text='External API ID (e.g., MangaDex)', max_length=100),
        ),
        migrations.AddField(
            model_name='manga',
            name='external_source',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='manga',
            name='favorite_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='manga',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manga',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manga',
            name='is_official',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manga',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manga',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manga',
            name='keywords',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='manga',
            name='last_chapter_added',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manga',
            name='last_external_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manga',
            name='meta_description',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='manga',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='manga',
            name='original_language',
            field=models.CharField(default='ja', max_length=10),
        ),
        migrations.AddField(
            model_name='manga',
            name='original_source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='manga',
            name='serialization',
            field=models.CharField(blank=True, help_text='Magazine or platform', max_length=100),
        ),
        migrations.AddField(
            model_name='manga',
            name='synopsis',
            field=models.TextField(blank=True, help_text='Short summary'),
        ),
        migrations.AddField(
            model_name='manga',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='manga/thumbnails/'),
        ),
        migrations.AddField(
            model_name='manga',
            name='total_ratings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='manga',
            name='total_volumes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='readinghistory',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='readinghistory',
            name='last_device',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='readinghistory',
            name='last_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='readinghistory',
            name='rating_reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='readinghistory',
            name='reading_status',
            field=models.CharField(choices=[('reading', 'Reading'), ('completed', 'Completed'), ('dropped', 'Dropped'), ('plan_to_read', 'Plan to Read'), ('on_hold', 'On Hold')], default='reading', max_length=20),
        ),
        migrations.AddField(
            model_name='readinghistory',
            name='session_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='readinghistory',
            name='total_reading_time',
            field=models.PositiveIntegerField(default=0, help_text='Total reading time in seconds'),
        ),
        migrations.AddField(
            model_name='userfavorite',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userfavorite',
            name='notes',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='userfavorite',
            name='notification_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userfavorite',
            name='priority',
            field=models.PositiveIntegerField(default=0, help_text='Priority order for user (0=highest priority)'),
        ),
        migrations.AddField(
            model_name='userfavorite',
            name='tags',
            field=models.JSONField(default=list, help_text='Custom tags added by user'),
        ),
        migrations.AddField(
            model_name='userfavorite',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_genres',
            field=models.ManyToManyField(blank=True, help_text="User's preferred genres", to='manga.genre'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='language_preference',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notification_settings',
            field=models.JSONField(default=manga.models.base.get_default_notification_settings, help_text='Notification preferences'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='premium_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='privacy_settings',
            field=models.JSONField(default=manga.models.base.get_default_privacy_settings, help_text='Privacy settings'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_reading_time',
            field=models.PositiveIntegerField(default=0, help_text='Total reading time in seconds'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='chapter_number',
            field=models.DecimalField(decimal_places=2, help_text='Allows fractional chapters like 1.5', max_digits=6),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='color_code',
            field=models.CharField(default='#007bff', help_text='Hex color code', max_length=7),
        ),
        migrations.AlterField(
            model_name='manga',
            name='author',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='manga',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='manga',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='readinghistory',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reading_history', to='manga.chapter'),
        ),
        migrations.AlterField(
            model_name='readinghistory',
            name='manga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_history', to='manga.manga'),
        ),
        migrations.AlterField(
            model_name='readinghistory',
            name='progress_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='readinghistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userfavorite',
            name='manga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favorites', to='manga.manga'),
        ),
        migrations.AlterField(
            model_name='userfavorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='reading_preferences',
            field=models.JSONField(default=manga.models.base.get_default_reading_preferences, help_text='User reading preferences'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['manga', 'chapter_number', 'is_published'], name='manga_chapt_manga_i_a2a080_idx'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['is_published', 'release_date'], name='manga_chapt_is_publ_3406fd_idx'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['manga', 'is_published', '-chapter_number'], name='manga_chapt_manga_i_a636d2_idx'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['-created_at'], name='manga_chapt_created_0c5af7_idx'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['manga', '-published_at'], name='manga_chapt_manga_i_c2cce5_idx'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['is_published', '-published_at'], name='manga_chapt_is_publ_8ba7ec_idx'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['scheduled_release'], name='manga_chapt_schedul_c6f341_idx'),
        ),
        migrations.AddIndex(
            model_name='genre',
            index=models.Index(fields=['is_popular', 'manga_count'], name='manga_genre_is_popu_400cde_idx'),
        ),
        migrations.AddIndex(
            model_name='genre',
            index=models.Index(fields=['parent_genre', 'display_order'], name='manga_genre_parent__252d8c_idx'),
        ),
        migrations.AddIndex(
            model_name='genre',
            index=models.Index(fields=['name'], name='manga_genre_name_3b6cbe_idx'),
        ),
        migrations.AddIndex(
            model_name='genre',
            index=models.Index(fields=['is_active', 'is_popular'], name='manga_genre_is_acti_0401f2_idx'),
        ),
        migrations.AddIndex(
            model_name='readinghistory',
            index=models.Index(fields=['user', '-last_read_at'], name='manga_readi_user_id_240fa5_idx'),
        ),
        migrations.AddIndex(
            model_name='readinghistory',
            index=models.Index(fields=['manga', '-last_read_at'], name='manga_readi_manga_i_f14371_idx'),
        ),
        migrations.AddIndex(
            model_name='readinghistory',
            index=models.Index(fields=['user', 'reading_status'], name='manga_readi_user_id_7caca9_idx'),
        ),
        migrations.AddIndex(
            model_name='readinghistory',
            index=models.Index(fields=['user', 'progress_percentage'], name='manga_readi_user_id_2afa2f_idx'),
        ),
        migrations.AddIndex(
            model_name='readinghistory',
            index=models.Index(fields=['reading_status', '-last_read_at'], name='manga_readi_reading_068494_idx'),
        ),
        migrations.AddIndex(
            model_name='userfavorite',
            index=models.Index(fields=['user', '-added_at'], name='manga_userf_user_id_2899ef_idx'),
        ),
        migrations.AddIndex(
            model_name='userfavorite',
            index=models.Index(fields=['manga', '-added_at'], name='manga_userf_manga_i_610160_idx'),
        ),
        migrations.AddIndex(
            model_name='userfavorite',
            index=models.Index(fields=['user', 'is_private'], name='manga_userf_user_id_37b5f7_idx'),
        ),
        migrations.AddIndex(
            model_name='userfavorite',
            index=models.Index(fields=['user', 'notification_enabled'], name='manga_userf_user_id_5b5e38_idx'),
        ),
        migrations.AddIndex(
            model_name='userfavorite',
            index=models.Index(fields=['user', 'priority', '-added_at'], name='manga_userf_user_id_058c8d_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user', 'is_verified'], name='manga_userp_user_id_c400b7_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['country'], name='manga_userp_country_3a2a37_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['is_premium', 'premium_expires_at'], name='manga_userp_is_prem_900762_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['language_preference'], name='manga_userp_languag_dad60d_idx'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manga.chapter'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='manga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manga.manga'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookmarkpage',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_pages', to='manga.chapter'),
        ),
        migrations.AddField(
            model_name='bookmarkpage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_pages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chapterview',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='manga.chapter'),
        ),
        migrations.AddField(
            model_name='chapterview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapter_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='manga.chapter'),
        ),
        migrations.AddField(
            model_name='comment',
            name='manga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='manga.manga'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='manga.comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentlike',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='manga.comment'),
        ),
        migrations.AddField(
            model_name='commentlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mangagenre',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manga_genres', to='manga.genre'),
        ),
        migrations.AddField(
            model_name='mangagenre',
            name='manga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manga_genres', to='manga.manga'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='genres',
            field=models.ManyToManyField(blank=True, through='manga.MangaGenre', to='manga.genre'),
        ),
        migrations.AddField(
            model_name='mangarating',
            name='manga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='manga.manga'),
        ),
        migrations.AddField(
            model_name='mangarating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manga_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mangatag',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mangatag',
            name='manga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manga_tags', to='manga.manga'),
        ),
        migrations.AddField(
            model_name='notification',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='manga.chapter'),
        ),
        migrations.AddField(
            model_name='notification',
            name='manga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='manga.manga'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ratinghelpful',
            name='rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpfulness_votes', to='manga.mangarating'),
        ),
        migrations.AddField(
            model_name='ratinghelpful',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='sitesettings',
            index=models.Index(fields=['key'], name='manga_sites_key_8f0df3_idx'),
        ),
        migrations.AddIndex(
            model_name='sitesettings',
            index=models.Index(fields=['category', 'key'], name='manga_sites_categor_9ceab2_idx'),
        ),
        migrations.AddIndex(
            model_name='sitesettings',
            index=models.Index(fields=['is_public'], name='manga_sites_is_publ_c7f259_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['type', 'usage_count'], name='manga_tag_type_e30558_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['name'], name='manga_tag_name_c789dc_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['type', 'name'], name='manga_tag_type_47cbd4_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['is_system', 'type'], name='manga_tag_is_syst_785eca_idx'),
        ),
        migrations.AddField(
            model_name='mangatag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manga_tags', to='manga.tag'),
        ),
        migrations.AddField(
            model_name='manga',
            name='tags',
            field=models.ManyToManyField(blank=True, through='manga.MangaTag', to='manga.tag'),
        ),
        migrations.AddIndex(
            model_name='manga',
            index=models.Index(fields=['title'], name='manga_manga_title_b5a3dc_idx'),
        ),
        migrations.AddIndex(
            model_name='manga',
            index=models.Index(fields=['author'], name='manga_manga_author_cd5014_idx'),
        ),
        migrations.AddIndex(
            model_name='manga',
            index=models.Index(fields=['status', 'is_featured'], name='manga_manga_status_22a51b_idx'),
        ),
        migrations.AddIndex(
            model_name='manga',
            index=models.Index(fields=['-average_rating', '-view_count'], name='manga_manga_average_31eaed_idx'),
        ),
        migrations.AddIndex(
            model_name='manga',
            index=models.Index(fields=['-updated_at'], name='manga_manga_updated_82f022_idx'),
        ),
        migrations.AddIndex(
            model_name='manga',
            index=models.Index(fields=['is_popular', 'is_trending'], name='manga_manga_is_popu_6925f4_idx'),
        ),
        migrations.AddIndex(
            model_name='manga',
            index=models.Index(fields=['external_id', 'external_source'], name='manga_manga_externa_f258f4_idx'),
        ),
        migrations.AddIndex(
            model_name='manga',
            index=models.Index(fields=['is_featured', '-updated_at'], name='manga_manga_is_feat_e56450_idx'),
        ),
        migrations.AddIndex(
            model_name='manga',
            index=models.Index(fields=['status', 'is_completed'], name='manga_manga_status_bac0c2_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action_type', '-created_at'], name='manga_activ_action__3f9227_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', '-created_at'], name='manga_activ_user_id_9999b2_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['-created_at'], name='manga_activ_created_6633f4_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['severity', '-created_at'], name='manga_activ_severit_190522_idx'),
        ),
        migrations.AddIndex(
            model_name='bookmarkpage',
            index=models.Index(fields=['user', '-created_at'], name='manga_bookm_user_id_405543_idx'),
        ),
        migrations.AddIndex(
            model_name='bookmarkpage',
            index=models.Index(fields=['chapter', 'page_number'], name='manga_bookm_chapter_daa016_idx'),
        ),
        migrations.AddIndex(
            model_name='bookmarkpage',
            index=models.Index(fields=['user', 'bookmark_type'], name='manga_bookm_user_id_59e8c9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bookmarkpage',
            unique_together={('user', 'chapter', 'page_number')},
        ),
        migrations.AddIndex(
            model_name='chapterview',
            index=models.Index(fields=['chapter', '-created_at'], name='manga_chapt_chapter_ae10d1_idx'),
        ),
        migrations.AddIndex(
            model_name='chapterview',
            index=models.Index(fields=['user', '-created_at'], name='manga_chapt_user_id_8c2c6d_idx'),
        ),
        migrations.AddIndex(
            model_name='chapterview',
            index=models.Index(fields=['ip_address', '-created_at'], name='manga_chapt_ip_addr_0aebd8_idx'),
        ),
        migrations.AddIndex(
            model_name='chapterview',
            index=models.Index(fields=['device_type', '-created_at'], name='manga_chapt_device__a98b46_idx'),
        ),
        migrations.AddIndex(
            model_name='chapterview',
            index=models.Index(fields=['country_code', '-created_at'], name='manga_chapt_country_c4b664_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['manga', '-created_at'], name='manga_comme_manga_i_d0d999_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['chapter', '-created_at'], name='manga_comme_chapter_c88128_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent', 'created_at'], name='manga_comme_parent__9b1378_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user', '-created_at'], name='manga_comme_user_id_33249e_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['is_approved', '-created_at'], name='manga_comme_is_appr_7189f5_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['is_spoiler', '-created_at'], name='manga_comme_is_spoi_d85a83_idx'),
        ),
        migrations.AddIndex(
            model_name='commentlike',
            index=models.Index(fields=['comment', 'vote_type'], name='manga_comme_comment_eb0615_idx'),
        ),
        migrations.AddIndex(
            model_name='commentlike',
            index=models.Index(fields=['user', '-created_at'], name='manga_comme_user_id_a94b65_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='commentlike',
            unique_together={('user', 'comment')},
        ),
        migrations.AddIndex(
            model_name='mangagenre',
            index=models.Index(fields=['manga', 'is_primary'], name='manga_manga_manga_i_010491_idx'),
        ),
        migrations.AddIndex(
            model_name='mangagenre',
            index=models.Index(fields=['genre', 'is_primary'], name='manga_manga_genre_i_3e3ee7_idx'),
        ),
        migrations.AddIndex(
            model_name='mangagenre',
            index=models.Index(fields=['manga', 'genre'], name='manga_manga_manga_i_c77a38_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mangagenre',
            unique_together={('manga', 'genre')},
        ),
        migrations.AddIndex(
            model_name='mangarating',
            index=models.Index(fields=['manga', '-rating', '-created_at'], name='manga_manga_manga_i_bf7661_idx'),
        ),
        migrations.AddIndex(
            model_name='mangarating',
            index=models.Index(fields=['manga', 'is_approved'], name='manga_manga_manga_i_dcb37a_idx'),
        ),
        migrations.AddIndex(
            model_name='mangarating',
            index=models.Index(fields=['user', '-created_at'], name='manga_manga_user_id_871661_idx'),
        ),
        migrations.AddIndex(
            model_name='mangarating',
            index=models.Index(fields=['rating', '-helpful_votes'], name='manga_manga_rating_819f31_idx'),
        ),
        migrations.AddIndex(
            model_name='mangarating',
            index=models.Index(fields=['is_approved', '-created_at'], name='manga_manga_is_appr_3c16b0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mangarating',
            unique_together={('user', 'manga')},
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='manga_notif_user_id_a5003e_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['-created_at', 'expires_at'], name='manga_notif_created_eb57d4_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['type', '-created_at'], name='manga_notif_type_8ae9af_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'type', 'is_read'], name='manga_notif_user_id_b0be70_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['priority', '-created_at'], name='manga_notif_priorit_c3503b_idx'),
        ),
        migrations.AddIndex(
            model_name='ratinghelpful',
            index=models.Index(fields=['rating', 'vote_type'], name='manga_ratin_rating__7e522e_idx'),
        ),
        migrations.AddIndex(
            model_name='ratinghelpful',
            index=models.Index(fields=['user', '-created_at'], name='manga_ratin_user_id_09dcd2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ratinghelpful',
            unique_together={('user', 'rating')},
        ),
        migrations.AddIndex(
            model_name='mangatag',
            index=models.Index(fields=['manga'], name='manga_manga_manga_i_b74b24_idx'),
        ),
        migrations.AddIndex(
            model_name='mangatag',
            index=models.Index(fields=['tag'], name='manga_manga_tag_id_7b25e8_idx'),
        ),
        migrations.AddIndex(
            model_name='mangatag',
            index=models.Index(fields=['manga', 'tag'], name='manga_manga_manga_i_8ad22c_idx'),
        ),
        migrations.AddIndex(
            model_name='mangatag',
            index=models.Index(fields=['created_by', 'tag'], name='manga_manga_created_531715_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mangatag',
            unique_together={('manga', 'tag')},
        ),
    ]
