# Generated by Django 5.2.5 on 2025-09-01 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0001_initial'),
    ]

    operations = [
    ]
