# Generated by Django 5.2.5 on 2025-09-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0002_auto_20250901_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='user_agent',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
