# Generated by Django 5.2.5 on 2026-04-05 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manga", "0003_alter_activitylog_user_agent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("session_id", models.CharField(blank=True, max_length=100)),
                ("path", models.CharField(max_length=500)),
                ("referrer", models.URLField(blank=True, max_length=500)),
                ("query_string", models.CharField(blank=True, max_length=500)),
                ("user_agent", models.TextField(blank=True, max_length=500)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("desktop", "Desktop"),
                            ("mobile", "Mobile"),
                            ("tablet", "Tablet"),
                        ],
                        default="desktop",
                        max_length=20,
                    ),
                ),
                ("country_code", models.CharField(blank=True, max_length=2)),
                ("country_name", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="site_visits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Visit",
                "verbose_name_plural": "Site Visits",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="manga_sitev_created_913338_idx"
                    ),
                    models.Index(
                        fields=["ip_address", "-created_at"],
                        name="manga_sitev_ip_addr_bc8b38_idx",
                    ),
                    models.Index(
                        fields=["country_code", "-created_at"],
                        name="manga_sitev_country_e2e2db_idx",
                    ),
                    models.Index(
                        fields=["device_type", "-created_at"],
                        name="manga_sitev_device__5b8b52_idx",
                    ),
                    models.Index(
                        fields=["path", "-created_at"],
                        name="manga_sitev_path_57433e_idx",
                    ),
                ],
            },
        ),
    ]
